name: qr_scanner_monorepo
packages:
  - apps/**
  - packages/**

scripts:
  bootstrap: melos bootstrap
  analyze: melos exec -- flutter analyze
  test: melos exec -- flutter test
  clean: melos exec -- flutter clean
