name: qr_scanner
description: "Módulo para escanear códigos QR con integración nativa."
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  mobile_scanner: ^3.4.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.3
  build_runner: ^2.4.6

flutter:
